services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=wordpress
    ports:
      - "33060:3306"

  wordpress:
    image: wordpress:latest
    links:
      - db
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=yourpassword
    ports:
      - "80:80"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - nginx_data:/var/www/html
    links:
      - wordpress
    environment:
      - NGINX_MAIL_FROM=example@example.com
      - NGINX_MAIL_HOST=smtp.example.com
      - NGINX_MAIL_PORT=587
      - NGINX_MAIL_SECURE=465
      - NGINX_MAIL_MAILER=smtp
      - NGINX_MAIL_USERNAME=yourname
      - NGINX_MAIL_PASSWORD=yourpassword

volumes:
  db_data:
  wordpress_data:
  nginx_data:
